fix(ci): set macOS SDKROOT and sysroot to resolve missing frameworks

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -57,10 +57,13 @@ jobs:
             os: windows-latest
             name: portweaver-windows-x86_64-msvc.exe
 
-          # Windows arm64
-          - target: aarch64-windows-msvc
-            os: windows-11-arm
-            name: portweaver-windows-aarch64-msvc.exe
+          # # Windows arm64 failed yet
+          # - target: aarch64-windows-gnu
+          #   os: windows-11-arm
+          #   name: portweaver-windows-aarch64-gnu.exe
+          # - target: aarch64-windows-msvc
+          #   os: windows-11-arm
+          #   name: portweaver-windows-aarch64-msvc.exe
 
           # macOS
           - target: x86_64-macos
@@ -91,6 +94,7 @@ jobs:
         if: ${{ !matrix.custom_golang }}
         with:
           go-version: '1.25.7'
+          cache-dependency-path: "**/go.sum"
 
       - name: Setup Go (Linux)
         if: runner.os == 'Linux' && matrix.custom_golang
@@ -108,9 +112,35 @@ jobs:
           echo "GOROOT=$PWD\go" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
           echo "$PWD\go\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
+      - name: Setup sysroot (macOS)
+        if: runner.os == 'macOS'
+        run:  |
+          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
+          SDK_PATH=$(xcrun --show-sdk-path)
+          LIB_PATH="$SDK_PATH/usr/lib/libresolv.tbd"
+
+          echo "SDK path: $SDK_PATH"
+          echo "Checking: $LIB_PATH"
+
+          if [ -f "$LIB_PATH" ]; then
+            echo "libresolv found:"
+            ls -l "$LIB_PATH"
+          else
+            echo "libresolv NOT found"
+            find "$SDK_PATH" -name "libresolv*" -print
+            exit 1
+          fi
+
+
+
       - name: Build
+        shell: bash
         run: |
-          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSmall -Duci=false -Dubus=false -Dfrpc=true -Dddns=true
+          ZIG_FLAGS=""
+          if [ "${{ runner.os }}" == "macOS" ]; then
+            ZIG_FLAGS="--sysroot $SDKROOT"
+          fi
+          zig build $ZIG_FLAGS -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSmall -Duci=false -Dubus=false -Dfrpc=true -Dddns=true
 
       - name: Prepare Artifact (Linux)
         if: runner.os == 'Linux'
